name: disvm

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        flavor: [ 'Debug', 'Release' ]
    steps:
    - uses: actions/checkout@v2
    - name: Generate disvm
      run: build.cmd generate -build ${{ matrix.flavor }}
      shell: cmd
    - name: Build disvm
      run: build.cmd ${{ matrix.flavor }}
      shell: cmd
